### ISSUE TITLE
Excel Addin Returning #Value on Windows 11 for ARM

### ISSUE THREAD

**Issue by jamesdlow** [quandl/quandl-excel-windows#40]
I'm trying to use the addin on Windows 11 for ARM. Overall the Addin UI works flawlessly. Unfortunately once a formula has been created though, the addin returns #Value.

If formulas are turned off it does managed to return the formulas are turned off message, but maybe that is returned from the function and not written into the cells when data is actually returned?

**Comment by jamesdlow** [comment]
Here's the log from my recent requests

2021-11-29T04-00-54Z : Object reference not set to an instance of an object.
2021-11-29T04-00-54Z : [StackTrace,    at Quandl.Excel.UDF.Functions.Helpers.Tools.GetBoolValue(Object referenceOrString)
   at Quandl.Excel.UDF.Functions.UserDefinedFunctions.Timeseries.QSERIES(Object rawQuandlCodeColumns, Object rawDates, String rawCollapse, String rawOrder, String rawTransformation, Object rawLimit, String rawHeader, String rawDateColumn, String rawTranspose)] 0
2021-11-29T04-01-00Z : Object reference not set to an instance of an object.
2021-11-29T04-01-00Z : [StackTrace,    at Quandl.Excel.UDF.Functions.Helpers.Tools.GetBoolValue(Object referenceOrString)
   at Quandl.Excel.UDF.Functions.UserDefinedFunctions.Timeseries.QSERIES(Object rawQuandlCodeColumns, Object rawDates, String rawCollapse, String rawOrder, String rawTransformation, Object rawLimit, String rawHeader, String rawDateColumn, String rawTranspose)] 0

**Comment by couture-ql** [comment]
Hi @jamesdlow, we actually have a fix in the works and will be out in an upcoming release.

Once it's up, we'll appreciate any feedback to know if your use-case was resolved.

**Comment by jamesdlow** [comment]
Is that the 4.0.0 version? I'll try it straight away.

**Comment by jamesdlow** [comment]
Still experiencing the same issue.

**Comment by govert** [comment]
@jamesdlow Is this running on a M1 mac?
This discussion might relate: https://groups.google.com/g/exceldna/c/jCee3l0lzjM/m/3MId9svhAQAJ

**Comment by govert** [comment]
I wonder if, following the linked discussion, you could experiment a bit with the signature of the function - trying a short one with few arguments, for example.

**Comment by jamesdlow** [comment]
A possible workaround might be to have an option on the Addin to enable returning arrays direct from the formula rather than writing into the cells of the spreadsheet. Office v16 now supports automatic spillover of array functions with both a 365 subscription on 2019 standalone purchase.

**Comment by jamesdlow** [comment]
It can be an option, so people that want the old behavior can keep it.
